version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rentx
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/rentx
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rentx
    volumes:
      - ./data:/var/lib/postgresql/data
    

